SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
SELECT * FROM tblAuthor;
SELECT * FROM tblAuthorBook;
SELECT * FROM tblBook;
SELECT * FROM tblCheckouts;
SELECT * FROM tblReservations;
SELECT * FROM tblUsers;
SELECT * FROM tblUserUType;
SELECT * FROM tblUType;